### ISSUE TITLE
Version number in ResourceManifest 

### ISSUE THREAD

**Issue by RolfVeinoeSorensen** [devworx-au/Devworx.CodePrettify#1]
The ResourceManifest.cs in this module uses .SetVersion("r298") which does not work in Orchard 1.9.1 described here https://github.com/OrchardCMS/Orchard/issues/5283

The fix is simple just alter to .SetVersion("1.298") the 3 places in ResourceManifest.cs and this module will run fine with Orchard 1.9.1

**Comment by petedavis** [comment]
Thanks @RolfVeinoeSorensen 

I have pushed an update to the gallery.

**Comment by RolfVeinoeSorensen** [comment]
Very cool now your excellent module works for everyone with 1.9.1
